#!/usr/bin/env bash
set -euo pipefail

# verify-artifacts.sh
# Build and verify kernel artifact hashes for reproducibility checks.
#
# Default behavior:
# - run ./build.sh --allow-dirty
# - compare build/out artifact hashes to vendors/artifacts.lock
#
# Write mode:
# - run ./build.sh --allow-dirty
# - write current hashes to vendors/artifacts.lock

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
OUT_DIR="${ROOT}/build/out"
MANIFEST="${ROOT}/vendors/artifacts.lock"

MODE="verify"      # verify | write
RUN_BUILD=1        # 1=build before compare/write
ALLOW_DIRTY=1      # 1=pass --allow-dirty to build.sh

ARTIFACTS=(
  "kernel_pi1541.img"
  "kernel_chainloader.img"
  "kernel_service.img"
  "kernel_service.lz4"
)

die() { echo "ERROR: $*" >&2; exit 1; }
log() { echo "$@" >&2; }

usage() {
  cat <<'EOF'
Usage:
  ./tools/verify-artifacts.sh [--write] [--manifest=<path>] [--skip-build] [--no-allow-dirty]

Modes:
  (default)  Build and verify build/out artifact hashes against manifest.
  --write    Build and (re)write manifest with current artifact hashes.

Options:
  --manifest=<path>  Use a custom manifest path (default: vendors/artifacts.lock)
  --skip-build       Do not call build.sh (use existing build/out artifacts)
  --no-allow-dirty   Build without --allow-dirty
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --write) MODE="write"; shift ;;
    --manifest=*) MANIFEST="${1#*=}"; shift ;;
    --skip-build) RUN_BUILD=0; shift ;;
    --no-allow-dirty) ALLOW_DIRTY=0; shift ;;
    -h|--help) usage; exit 0 ;;
    *) die "unknown arg: $1" ;;
  esac
done

if [[ "$RUN_BUILD" -eq 1 ]]; then
  if [[ "$ALLOW_DIRTY" -eq 1 ]]; then
    "${ROOT}/build.sh" --allow-dirty
  else
    "${ROOT}/build.sh"
  fi
fi

declare -A actual_sha
declare -A actual_size

for artifact in "${ARTIFACTS[@]}"; do
  path="${OUT_DIR}/${artifact}"
  [[ -f "$path" ]] || die "missing artifact: $path"
  actual_sha["$artifact"]="$(sha256sum "$path" | awk '{print $1}')"
  actual_size["$artifact"]="$(stat -c '%s' "$path")"
done

toolchain_human="$(grep -E '^toolchain_human=' "${ROOT}/vendors/toolchain.lock" | head -n1 | cut -d= -f2-)"
[[ -n "${toolchain_human:-}" ]] || die "missing toolchain_human in vendors/toolchain.lock"
source_commit="$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || true)"
[[ -n "${source_commit:-}" ]] || source_commit="unknown"

if [[ "$MODE" == "write" ]]; then
  mkdir -p "$(dirname "$MANIFEST")"
  {
    echo "# Kernel artifact manifest for reproducibility checks."
    echo "# Generated by tools/verify-artifacts.sh --write"
    echo "# Format: file <name> <sha256> <bytes>"
    echo "toolchain_human=${toolchain_human}"
    echo "source_commit=${source_commit}"
    for artifact in "${ARTIFACTS[@]}"; do
      echo "file ${artifact} ${actual_sha[$artifact]} ${actual_size[$artifact]}"
    done
  } > "${MANIFEST}"
  log "Wrote artifact manifest: ${MANIFEST}"
  exit 0
fi

[[ -f "$MANIFEST" ]] || die "manifest not found: ${MANIFEST} (run with --write)"

declare -A expected_sha
declare -A expected_size
expected_toolchain_human=""
expected_commit=""

while IFS= read -r line; do
  [[ -z "$line" || "${line:0:1}" == "#" ]] && continue
  case "$line" in
    toolchain_human=*)
      expected_toolchain_human="${line#toolchain_human=}"
      ;;
    source_commit=*)
      expected_commit="${line#source_commit=}"
      ;;
    file\ *)
      read -r kind name sha size extra <<<"$line"
      [[ "$kind" == "file" && -n "${name:-}" && -n "${sha:-}" && -n "${size:-}" && -z "${extra:-}" ]] \
        || die "invalid manifest line: $line"
      expected_sha["$name"]="$sha"
      expected_size["$name"]="$size"
      ;;
    *)
      die "unknown manifest line: $line"
      ;;
  esac
done < "$MANIFEST"

[[ -n "${expected_toolchain_human:-}" ]] || die "manifest missing toolchain_human"
[[ "${expected_toolchain_human}" == "${toolchain_human}" ]] \
  || die "toolchain_human mismatch: expected '${expected_toolchain_human}', got '${toolchain_human}'"

if [[ -n "${expected_commit:-}" && "${expected_commit}" != "unknown" && "${source_commit}" != "unknown" ]]; then
  [[ "${expected_commit}" == "${source_commit}" ]] \
    || die "source_commit mismatch: expected ${expected_commit}, got ${source_commit}"
fi

ok=1
for artifact in "${ARTIFACTS[@]}"; do
  if [[ -z "${expected_sha[$artifact]:-}" || -z "${expected_size[$artifact]:-}" ]]; then
    log "missing expected entry for ${artifact}"
    ok=0
    continue
  fi
  if [[ "${expected_sha[$artifact]}" != "${actual_sha[$artifact]}" ]]; then
    log "sha mismatch for ${artifact}"
    log "  expected: ${expected_sha[$artifact]}"
    log "  actual:   ${actual_sha[$artifact]}"
    ok=0
  fi
  if [[ "${expected_size[$artifact]}" != "${actual_size[$artifact]}" ]]; then
    log "size mismatch for ${artifact}"
    log "  expected: ${expected_size[$artifact]}"
    log "  actual:   ${actual_size[$artifact]}"
    ok=0
  fi
done

if [[ "$ok" -ne 1 ]]; then
  die "artifact verification failed"
fi

log "OK: artifact hashes verified against ${MANIFEST}"
